<?php

namespace Anditsung\Manufacture\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProductType extends Model
{
    protected $table = 'manufacture_product_types';

    protected $fillable = [
        'name',
        'user_id',
        'active'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($product_type) {
            if(! $product_type->user_id) {
                $product_type->user_id = auth()->user()->id;
            }
        });
    }

    public function delete()
    {
        $this->setKeysForSaveQuery($this->newModelQuery())->update(['active' => false]);

        return true;
    }

    public function user() : BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
